<?php

/**
 * Implements hook_filter_info().
 */
function seooptim_filter_info() {
  $filters['seooptim_filter'] = array(
    'title' => t('SEO Optim Filter'),
    'description' => t('Make SEO optimizations on content.'),
    'process callback' => '_seooptim_filter',
  );
  return $filters;

}
/**
 * Implements hook_filter().
 */
function _seooptim_filter($text, $filter) {
  $text = preg_replace_callback('/<img[^>]*(alt="")[^>]*src="([^"]*)"[^>]*>/', '_seooptim_filter_imgalt', $text);
  return $text;
}

function _seooptim_filter_imgalt($matches) {
	$src = $matches[2];
	$src_array = explode("/", $src);
	$alt = array_pop($src_array); // get file name
	$src_array = explode(".", $alt);
	array_pop($src_array); // Delete extension
	$alt = implode(' ', $src_array);
	$alt = str_replace(array('-','_'), array(' ',' '), $alt);
	return str_replace('alt=""', 'alt="' . check_markup($alt, 'plain_text') . '"', $matches[0]);
}

function seooptim_preprocess_content_field(&$variables) {
	if($variables['field']['widget']['type'] == 'imagefield_widget') {
		foreach($variables['items'] as $key=>$image) {
			if(empty($variables['items'][$key]['data']['alt'])) {
				if(!empty($variables['items'][$key]['data']['description'])) {
					$alt = $variables['items'][$key]['data']['description'];
				}
				else if(!empty($variables['items'][$key]['data']['title'])) {
					$alt = $variables['items'][$key]['data']['title'];
				}
				else {
					$alt = $variables['node']->title;
				}
				$alt = check_plain($alt);
				//$variables['items'][$key]['data']['alt'] = $alt;
				$variables['items'][$key]['view'] = str_replace('alt=""', 'alt="' . $alt . '"', $variables['items'][$key]['view']);
			}
		}
	}
}

/**
 * Implements hook_node_view_alter().
 */
function seooptim_node_view_alter(&$build) {
	foreach($build as $field_name=>$field) {
		if(is_array($field)) {
			if($field['#field_type'] == 'image') { // It's an imagefield
        $node = $build['#node'];
				foreach($field['#items'] as $itimage=>$image) {
					if(empty($image['alt'])) {
						if(!empty($image['description'])) {
							$alt = $image['description'];
						}
						else if(!empty($image['title'])) {
							$alt = $image['title'];
						}
						else {
							$alt = $node->title;
						}
						$alt = check_plain($alt);
						$build[$field_name]['#items'][$itimage]['alt'] = $alt;
            if(empty($build[$field_name][$itimage]['#item']['alt'])) {
              $build[$field_name][$itimage]['#item']['alt'] = $alt;
            }
            //$build['node']->{$field_name}['und'][$itimage]['alt'] = $alt;
						//$build[$field_name][$itimage]['view'] = str_replace('alt=""', 'alt="'. $alt .'"', $build[$field_name][$itimage]['view']);
					}
				}
			}
		}
	}
}